fix: PR pipeline (#29)
* update README for correct virtual environment activation steps
* add failure condition for autopep8 step in pull request workflow
* remove redundant Python setup and dependency installation steps from pull request workflow
* add unit tests stage

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: abu271 <abu271@users.noreply.github.com>

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -1,12 +1,12 @@
-name: Pull Request Linting
+name: Pull Request Checks
 
 on:
   pull_request:
     branches: [ master ]
 
 jobs:
-  lint:
-    name: Lint
+  build:
+    name: Build
     runs-on: ubuntu-latest
     
     steps:
@@ -20,13 +20,37 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+    # upload artifacts
+    - name: Upload math result for job 1
+      uses: actions/upload-artifact@v4
+      with:
+        name: bookapi-artifact
+        path: |
+            app/
+            Dockerfile
+            docker-compose.yml
+            requirements.txt
+            version.txt
+        retention-days: 1
+  lint:
+    name: Lint
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 0  # Ensure the full commit history is fetched
+        ref: ${{ github.event.pull_request.head.ref }}
     # format code with autopep8
     - name: autopep8
-      uses: peter-evans/autopep8@v1
+      id: autopep8
+      uses: peter-evans/autopep8@v2
       with:
-        args: --recursive --in-place --aggressive --aggressive .
+        args: --exit-code --recursive --in-place --aggressive --aggressive .
     # create a pull request if autopep8 made changes
     - name: Create Pull Request
+      if: steps.autopep8.outputs.exit-code == 2
       uses: peter-evans/create-pull-request@v3
       with:
         commit-message: "lint: autopep8 action fixes"
@@ -35,9 +59,10 @@ jobs:
         labels: autopep8, automated pr
         reviewers: abu271
         branch: autopep8-patches
-    # lint code with flake8
-    - name: Lint with flake8
-      run: cd app && flake8
+    # fail if autopep8 made changes
+    - name: Fail if autopep8 made changes
+      if: steps.autopep8.outputs.exit-code == 2
+      run: exit 1
 
   test:
     name: Unit Tests
@@ -69,7 +94,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install --upgrade setuptools
-          if [ -f requirements.txt]; then pip install -r requirements.txt; fi
+          pip install -r requirements.txt
       # run python tests
       - name: Run test
         run: cd app && python manage.py test
